name: A-Plus Auto Poster

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Python 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: 필요 라이브러리 설치
        run: pip install requests beautifulsoup4
        
      - name: 로봇 가동
        run: python autobot.py
        
      - name: 변경사항 확인 및 푸시
        run: |
          git config --global user.name "AutoBot"
          git config --global user.email "bot@8222quick.com"
          git add _posts/*.md
          # 파일이 새로 생겼을 때만 커밋하도록 설정
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "신속한 배송 자동 포스팅 완료"
            git push
          else
            echo "새로 생성된 포스팅 파일이 없습니다."
          fi
